# Generated by Django 3.0.2 on 2020-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Age', models.DecimalField(decimal_places=3, max_digits=150)),
                ('Address', models.TextField()),
            ],
        ),
    ]
