# Generated by Django 3.0.2 on 2020-02-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='summary',
            field=models.TextField(default='This is a cool!'),
        ),
    ]
