# Generated by Django 3.0.2 on 2020-02-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mobiles_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Mobile',
        ),
    ]
