# Generated by Django 3.0.2 on 2020-02-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200229_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='title',
            field=models.TextField(),
        ),
    ]
