# Generated by Django 3.0.2 on 2020-02-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200229_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('summary', models.TextField(default='This is a cool!')),
                ('featured', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='title',
            field=models.TextField(),
        ),
    ]
